jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "This step will succeed."
        
      - name: Step 2 (Potentially Failing)
        run: exit 1
        continue-on-error: true  # Allow this step to fail
        
      - name: Step 3 (Notification)
        run: echo "This step runs regardless of previous step status."
        if: always()  # Run always, regardless of success or failure
        # Add a comment to the workflow run, issue, or pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Workflow completed!" > notification.md
          gh pr comment ${{ github.event.issue.number }} --body "$(cat notification.md)"