name: Deploy to Kubernetes

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create kubeconfig
      run: |
        mkdir ${HOME}/.kube
        echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
        cat ${HOME}/.kube/config
    - name: Use context
      run: kubectl config use-context $nameWhereDeploy

    - name: Deploy to K8s
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml

# Store the kube config of the cluster as a secret 
# Before storing as secret need to convert kubeconfig to base 64 (imp)(line 19)(and store in the directory created at line 18)\
# The secret name must be "KUBE_CONFIG" because kubeconfig is a keyword in k8 to determine where the kube config file
# kubectl doesnt need to be installed as it comes pre installed in ubuntu -latest . 
# if required use :- 
#      - name: Install kubectl #marketplace
#      uses: azure/setup-kubectl@v2.0
#      with:
#        version: 'v1.24.0' # default is latest stable
#      id: install