name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install AWS CLI
        uses: aws-cli/setup-aws-cli@v1
        with:
          aws-version: 2  
        id: aws

      - name: Install Dependencies
        run: npm install

      - name: Package Lambda Function
        run: npm run build  # Replace with your build command

      - name: Deploy Lambda
        run: |
          aws lambda update-function-code \
            --function-name FUNCTION_NAME \
            --zip-file fileb://dist/LAMBDA_PACKAGE.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


#Create an IAM role that allows your GitHub Actions workflow to interact with AWS Lambda. This role should have permissions to create or update Lambda functions, and it should trust the AWS service lambda.amazonaws.com.