jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "This step will succeed."
        
      - name: Step 2 (Potentially Failing)
        run: exit 1
        continue-on-error: true  # Allow this step to fail
        
      - name: Step 3 (Cleanup or Notification)
        run: echo "This step runs regardless of previous step status."
        if: failure()  # Run only if a previous step failed